mendersoftware/go-lib-micro

- LIC_FILES_CHKSUM.sha256
- config/config.go
- config/config_test.go
- config/testdata/config-empty.yaml
- routing/routing.go
- routing/routing_test.go
- strings/search.go
- strings/search_test.go
- vendor/github.com/spf13/viper/LICENSE
- vendor/github.com/spf13/viper/README.md
- vendor/github.com/spf13/viper/flags.go
- vendor/github.com/spf13/viper/util.go
- vendor/github.com/spf13/viper/viper.go
- vendor/vendor.json
prep for MEN-795 ('userauth' boilerplate) - factor out some more common packages:
- config
- routing (OPTIONS handling)
- string utils (search)
@bboozzoo @kjaskiewiczz
> Factor out common packages

- rest_utils/response_helpers.go
> rest: response helpers for error conditions in http handlers

- testing/response.go
copied from 'deployments'
Issues: MEN-796
> testing: http response testing utils

- testing/response.go
Issues:MEN-796
@bboozzoo @kjaskiewiczz
> testing: fix response utils

- testing/response.go
> testing: fix content type for json response

- rest_utils/paging.go
@bboozzoo @mchalski @maciejmrowiec
> Add pagination halper to the rest_utils package.

- log/log.go
- log/log_test.go
Add helper for adding logger to context
> log: add WithContext() helper

- requestid/utils.go
- requestid/utils_test.go
> requestid: add helper for packing request ID into context.Context

- store/utils.go
- store/utils_test.go
> store: util for multitenant database name generation

- identity/middleware.go
- store/utils.go
- store/utils_test.go
> store: fix DbFromContext helper

- identity/cmd/dumpidentity/dumpidentity.go
Minor fixes to `dumpidentity` tool
@mendersoftware/rndity @maciejmrowiec @GregorioDiStefano
> dumpidentity fix

- store/utils.go
- store/utils_test.go
@mendersoftware/rndity 
Needed for https://tracker.mender.io/browse/MEN-1440 and https://tracker.mender.io/browse/MEN-1439
> store: provide helper for extracting tenant ID from database name

- identity/middleware.go
- identity/middleware_test.go
> identity: include tenant ID in logger context

- requestid/middleware.go
- requestid/middleware_test.go
- requestid/utils.go
> requestid: make sure that requestid is properly saved to request context

- mongo/migrate/db.go
- mongo/migrate/db_test.go
- mongo/migrate/migrator_dummy.go
- mongo/migrate/migrator_simple.go
- mongo/testing/db.go
- vendor/github.com/mendersoftware/mendertesting/check_license_go_code.sh
- vendor/vendor.json
Changelog: None
Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>
> Update mendertesting dependency and affected copyright years.

- .travis.yml
- LICENSE
- LIC_FILES_CHKSUM.sha256
- mongo/dbtest/LICENSE
- mongo/dbtest/db.go
- mongo/migrate/db.go
- mongo/migrate/db_test.go
- mongo/migrate/migrator_dummy.go
- mongo/migrate/migrator_dummy_test.go
- mongo/migrate/migrator_simple.go
- mongo/migrate/migrator_simple_test.go
- mongo/migrate/mocks/Migration.go
- mongo/testing/db.go
Port of dbtest for new official mongo driver added.
Support for new driver in ./mongo
ChangeLog:title
Signed-off-by: Peter Grzybowski <peter@northern.tech>
> MEN-2453 Migrate to new mongo driver, porting dbtest and migrations

- plan/plans.go
- plan/plans_test.go
- plan/pricing.go
Central place to handle plans permissions 
see also: https://tracker.mender.io/browse/MEN-3008
example usage: https://github.com/mendersoftware/useradm-enterprise/pull/40/commits/350110a2e6e0a96fc1701e4995a2aecade6aa4a2#diff-58dcce776af1c084ee139709c64207cbR211
> Pricing plan module

- mongo/doc/bson.go
- mongo/doc/bson_test.go
- mongo/doc/ops.go
- mongo/doc/ops_test.go
Moved from deployments-enterprise since it will be used in the
open-source version, and possibly needed by other services in the
future.
> Mongo document utility library

- accesslog/middleware.go
Update logging middleware to enrich HTTP request logs with additional
fields. This allows indexing the extra fields using the EFK (or ELK)
stack and filter/aggregate on those fields using Kibana.
List of new fields:
- type: http (string)
- ts: timestamp with microsecond resolution (time)
- status: HTTP response status code (int)
- responsetime: response time in seconds (float64)
- byteswritten: number of bytes written (int)
- method: method of request (string)
- path: path of request URL (string)
- qs: query  of the URL (string)
Example log entry:
`time="2020-05-07T17:27:38+02:00" level=info msg="404 171μs GET /abc/test?a HTTP/1.1 - curl/7.64.1" byteswritten=30 file=middleware.go func="requestlog.(*RequestLogMiddleware).MiddlewareFunc.func1" line=45 method=GET path=/abc/test qs=a …
> MC-1352: enhance HTTP logs

- mongo/doc/bson.go
- mongo/doc/bson_test.go
- vendor/github.com/ant0ine/go-json-rest/rest/request.go
- vendor/github.com/ant0ine/go-json-rest/rest/test/util.go
- vendor/github.com/mendersoftware/mendertesting/.gitlab-ci-check-docker-build.yml
- vendor/modules.txt
Convenience function for transforming structs and maps to query-like documents.
> mongo/doc: bson.FlattenDocument for composing queries and upserts

- rest_utils/paging.go
- rest_utils/paging_test.go
> Fix: do not double-unquote URL parameters

- .gitlab-ci.yml
- which I missed in the review for #82
Changelog: None
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>
> reintroduced static golang checks

- ws/protomsg.go
It's more or less copy-paste from the design document...
> New subpackage "ws" containing the ProtoMsg definition

- mongo/migrate/migrator_dummy.go
- plan/pricing.go
- ws/protomsg.go
- ws/shell/model.go
ws-protocol shell module
ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>
> ws-proto: shell module

- ws/shell/model.go
> New message type: MessageTypeResizeShell

- ws/filetransfer/model.go
- ws/protomsg.go
ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>
> ws: File transfer

- ws/menderclient/model.go
- ws/portforward/model.go
- ws/protomsg.go
> ws: add constants for port-forwarding and mender client

- ws/filetransfer/model.go
- ws/protomsg.go
This is a provisional PR and is SUBJECT TO CHANGE.
> ws/filetransfer: Update protocol schemas

- ws/protomsg.go
This PR is a request for comment from all the backend folks.
In this commit I've added suggestive schema and docs for the handshake and introduction of versioning. I'd like as many as possible to take a look at this and provide comments and suggestions before we proceed with the required modifications to `mender-connect` and `deviceconnect`.
> ws: Introduce protocol versioning to ProtoMsg

- ws/portforward/model.go
> Improve the port-forward websocket protocol

- ws/portforward/model.go
> Updates to the port forward model

- identity/middleware_test.go
- identity/token.go
- identity/token_test.go
> MEN-4589: add the Trial claim to the JWT token

- store/v2/utils.go
- store/v2/utils_test.go
> MEN-4584: store/v2, single-database multitenancy model

- mongo/doc/bson.go
> DocumentFromStruct: if struct implements bson.Marshaler, use MarshalBSON

- store/v2/utils.go
> Use MarshallBSONOrDocumentFromStruct in store/v2

- accesslog/middleware_gin_test.go
- addons/addons.go
> MEN-4831: add monitor addon

- accesslog/exclude.go
- accesslog/middleware.go
- accesslog/middleware_gin.go
Changelog: Title
Ticket: None
Signed-off-by: Peter Grzybowski <peter@northern.tech>
> fix: Do not log successful health and alive requests via exludes.

- go.mod
- go.sum
- redis/redis.go
The redis package contains method for creating redis client.
Ticket: MC-7057
> feat: introduce redis package

- rbac/rbac.go
Changelog: Title
Ticket: MEN-6350
> feat: support for X-MEN-RBAC-Releases-Tags

- accesslog/middleware.go
This commit removes the Apache accesslog templating and message from the accesslogs (the log message contains the same information exposed by the log fields).
The useragent is consistently reported as the `useragent` field.
> fix(accesslog): Align ant0nie and gin-gonic middlewares
