testing/response.go
how it works:
- the CheckResponse accepts a ResponseChecker interface, delegates checking
the body, status, etc.
- different implementations of ResponseChecker can provide their own checking logic
- BaseResponse is a checker for 'any' content-type, and provides common funcs
for checking status, headers
- JSONResponse implements json unmarshalling for checking the body
Issues: MEN-796
=> testing: response utils now allow other content-types

mongo/migrate/migrator_simple.go, mongo/migrate/migrator_simple_test.go
Support a weird scenario when target version for migrations is lower than the
actual migrations. In this case, we skip the migration and log a warning.
=> mongo/migrate: skip migrations if target version is lower

apiclient/api_client.go, apiclient/api_client_test.go, apiclient/runner.go
the HttpRunner interface mimics http.Client and its Do(...) method.
the HttpApi implementation adds some Mender-specific request headers
to each request, and is designed to be used for internal calls between
Mender services.
Issues: MEN-1068
Changelog: None
@bboozzoo this implementation was lifted from your recent pull request do devauth, ping me if this needs further coordination
@maciejmrowiec @mendersoftware/rndity
=> apiclient: generic http client for inter-service calls

mongo/migrate/db.go, mongo/migrate/db_test.go, mongo/migrate/migrator_simple.go, mongo/migrate/migrator_simple_test.go, store/utils.go, store/utils_test.go
https://tracker.mender.io/browse/MEN-1243
- a simple low-level listing of tenant dbs according to conventions
- introduction of the idea of `automigrations` (as opposed to just checking db versions) into the migrator
note that even with multitenancy, the migrator works on a single db - the store will control iteration over tenant dbs.
@maciejmrowiec @mendersoftware/rndity
=> utils supporting multitenant migrations

mongo/migrate/migrator_dummy.go, mongo/migrate/migrator_dummy_test.go
needed e.g. by useradm.
Issues: MEN-1255
Changelog: None
@maciejmrowiec @mendersoftware/rndity
=> mongo/migrate: make dummy migrator multitenancy-aware

context/httpheader/header.go, context/httpheader/header_test.go, identity/token.go, identity/utils.go, identity/utils_test.go, log/log.go, log/log_test.go, requestid/utils.go, requestid/utils_test.go
The rationale behind this is that basic types are accessible everywhere, so it
is possible that someone may accidentally use the same value as the key and
overwrite existing Value in the context. A recommended solution for this is
using package private types. According to Go's equality rules:
Interface values are comparable. Two interface values are equal if they have
identical dynamic types and equal dynamic values or if both have value nil.
Since Key in context.Context is an interface{}, use of package private types
with either contstant non-nil value or value set at runtime will be sufficient.
@mendersoftware/rndity
=> global: avoid use of basic types as context.Context keys

accesslog/middleware.go, context/middleware.go, requestid/middleware.go, requestlog/middleware.go, requestlog/middleware_test.go
Request ID and associated logger will be kept in request context instead.
@mendersoftware/rndity
=> requestlog/requestid: stop using rest.Request.Env for keeping request logger and request ID

store/utils.go, store/utils_test.go
changelog: none
small util that will come in handy in `deployments` migrations.
@mendersoftware/rndity
=> store/utils: get db name for tenant

rest_utils/api_error.go, rest_utils/api_error_test.go
will be useful whenever we need to extract info from a downstream
service's error response.
current use case is propagating error messages re dev count limits
from devauth to the user via devadm.
changelog: none
=> rest_utils: helpers for parsing api error responses

rest_utils/response_helpers.go
till now it was only possible to return error code and log message with log level equal to error
now it will be possible to log message with any log level when returning HTTP error code
@maciejmrowiec @mchalski @PiotrPrzybylak @GregorioDiStefano
=> rest_utils: extend response helpers by adding possibility to log with different levels

mongo/dbtest/db.go, mongo/migrate/db_test.go, mongo/migrate/migrator_dummy.go, mongo/migrate/migrator_dummy_test.go, mongo/migrate/migrator_simple.go, mongo/migrate/migrator_simple_test.go, mongo/testing/db.go
To comply with the new mongodb driver, the client construct is used in
all cases as session was previously used. The renaming is done in order
not to confuse the term with the session construct of mongodb.
changelog: none
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>
=> Rename all `session` references to `client`

.gitlab-ci.yml
Fix unit tests coverage reports collection
The way we execute `go test` it will create multiple coverage.txt across
subfolders.
This is actually the same design used in many other backend repos.
=> Fix unit tests coverage reports collection

LICENSE, LIC_FILES_CHKSUM.sha256, identity/middleware.go, identity/middleware_test.go, identity/token.go, identity/token_test.go
Our services are using identity middleware to extract some claims (like sub, mender.tenant, etc.) from JWT and passed them to the context.
With this change, identity middleware will extract "mender.plan" claim also.
=> identity: handle "mender.plan" claim in the identity middleware

ratelimits/limits.go, ratelimits/limits_test.go
small step in:
https://tracker.mender.io/browse/MEN-3552
these structs are already used by 2 services, just making them common:
https://github.com/mendersoftware/tenantadm/pull/153
https://github.com/mendersoftware/deviceauth/pull/347
changelog: none
Signed-off-by: Marcin Chalczynski <m.chalczynski@gmail.com>
=> ratelimits: common structs for ratelimiting

mongo/dbtest/db.go, mongo/migrate/db.go
Changed GetMigrationInfo to sort by version (descending order) and removed deprecated flags from mongod command in unit test environment.
=> Convenience changes

rest_utils/api_error.go, rest_utils/response_helpers.go
Just a small inconsistency fix. Now the rest_utils response handlers use the ApiError defined in the same package, which doesn't capitalize the error field in the JSON structure.
=> Remove captialization of rest_utils error response helpers

log/log.go
Always ends on the wrong file because github.com/Sirupsen/logrus
switched to lower-case.
=> FIX: log.ContextHook missfire

identity/token.go, identity/token_test.go
Makes encoding and decoding a whole lot more straight forward.
=> identity: Make identity struct json representation match jwt claims

rest_utils/paging.go, rest_utils/paging_test.go
Current implementation adds the container hostname to the host of the
Link url.
=> MEN-3964: Switch to relative URLs for Link pagination header

identity/middleware.go, identity/token.go, identity/token_test.go
Passing the JWT as cookie allows passing the authorization token to downloadable URLs and upgrading to websockets from the browser.
=> Allow passing JWT as a cookie

identity/token.go, identity/token_test.go
Original fix by @mainnika #80
As pointed out in #80, there is a risk of encoding bad base64 tokens.
Moreover, the JWT specification [RFC 7519] specifies the URL-safe
variant of base64 encoding should be used.
=> identity: Use URL encoding to parse base64 claims

accesslog/middleware_gin.go, accesslog/middleware_gin_test.go
We will need to redact RawQuery and possibly url paths from sensitive
parameters. Moreover, using the 'unmodified' values breaks with the
go-json-rest version of the middleware.
=> Remove Path from LogParameters, add qs to default log context

accesslog/middleware_gin.go, accesslog/middleware_gin_test.go, identity/middleware.go, identity/middleware_test.go
This will break compatibility with the old version of the middleware, but since it's only in use by one service (mendersoftware/deviceconnect) I'll make sure to make the necessary adjustments.
=> Remove default regex from identity middleware and add panic recovery to accesslog

mongo/doc/bson.go, mongo/doc/bson_test.go
If the struct implements bson.Marshaler, and the MarshalBSON method
invokes mongo.doc.DocumentFromStruct, we have an infinte recursion. To
avoid that, providee a new method
mongo.doc.MarshallBSONOrDocumentFromStruct which uses the bson.Marshaler
interface is available, and revert DocumentFromStruct to the old
behaviour.
=> Avoid infinte recursion in mongo.doc.DocumentFromStruct

mongo/doc/bson.go, store/v2/utils.go, store/v2/utils_test.go
Conditionally adding the tenant_id field prevents reuse of multi-key indexes on the tenant_id key.
=> store/v2: Add "tenant_id" field unconditionally in WithTenantID

mongo/doc/bson.go, mongo/doc/bson_test.go
feat(mongo): inline support
Support for `bson:"inline"` tag was added to enable deviceauth database migrations to work with deviceauth's jwt.Token structure.
Changelog: All
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>
=> feat(deviceauth migrations): Add support for inline bson tags in DocumentFromStruct

.gitlab-ci.yml, mongo/testing/db.go, mongo/testing/db_env.go, mongo/testing/db_env_test.go
Introduce a new environment variable TEST_MONGO_URL which allows unit tests to use existing mongo server instead of installing mongod locally.
=> Use existing mongo server for unit tests

redis/redis.go
The error when parsing the connection string is not caught and will lead to panic.
=> chore: Fix redis connection string error handling

accesslog/middleware.go, accesslog/middleware_gin.go, accesslog/middleware_test.go
The new middleware aligns better with the gin counterpart. The responsetime is now logged with up to 3-digit precision in the appropriate unit.
=> fix: Improving legacy accesslog middleware by logging panic traces

accesslog/context.go, accesslog/middleware.go, accesslog/middleware_gin.go, log/log.go, rest_utils/response_helpers.go, rest_utils/response_helpers_test.go
This change will improve debugging in many situations as the accesslog contains all the information to trace back the callee that emitted the error. It also improves the log volume emitted from our services as the response error helpers now enrich the accesslog context.
=> Squash response helper errors into the accesslog entry

redis/redis.go
In k8s we're using the convinient connection scheme tcp-redis+srv that is needed to build a SRV connection string, but after constructing that, the scheme remains "tcp-redis+srv" and the redis connection fails. This fix force the "redis" scheme, after constructing the connection string.
Ticket: MEN-7035
Changelog: restore the right redis connection scheme
=> Redis connection string fix in K8s

ws/protomsg.go
The status hint code is a necessary hint for the server to determine what status to return.
=> chore: Extend the ProtoMsg.Error schema with a status field
